python-pyinsane (1.3.5-1) unstable; urgency=medium

  * Initial release. (Closes: #741881)

 -- Ross Vandegrift <ross@kallisti.us>  Thu, 20 Mar 2014 20:56:03 +0000
